version: "3"

services:
    backend:
        build: ./backend
        ports:
            - 3000:3000
        volumes:
            - ./backend:/data
    frontend:
        build: ./frontend
        ports:
            - 8080:8080
        volumes:
            - ./frontend/dist:/data
